<Project>
    <PropertyGroup Label="Package_Managing">
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <CentralPackageVersionOverrideEnabled>true</CentralPackageVersionOverrideEnabled>
    </PropertyGroup>

    <PropertyGroup Label="Package_Version">
        <MCFPVersionPrefix>0.1.0</MCFPVersionPrefix>
        <MCFPVersionSuffix></MCFPVersionSuffix>
        <MCFPVersion Condition="'$(MCFPVersionSuffix)' == ''">$(MCFPVersionPrefix)</MCFPVersion>
        <MCFPVersion Condition="'$(MCFPVersionSuffix)' != ''">$(MCFPVersionPrefix)-$(MCFPVersionSuffix)</MCFPVersion>
    </PropertyGroup>

    <ItemGroup Label="ThirdParty_Dependencies">
    </ItemGroup>

    <ItemGroup Label="Release_Dependencies" Condition="'$(Configuration)' == 'Release'">
    </ItemGroup>

    <ItemGroup Label="Debug_Dependencies" Condition="'$(Configuration)' == 'Debug'">
    </ItemGroup>
</Project>
